version: '3'

services:
  api:
    container_name: wongames_api
    image: andrerego/wongames-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'sk_test_51KQDfrCwrc5vNP3Ubef5pf5FH9LwbVbjmZoOBhgkQY3NHanx9igy077MZtpic2TbnKWydYzeHUDnlnhzTfEtVEDp00xiMMsOTv'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: andrerego/wongames-database:latest
    ports:
      - '5432:5432'
